server:
  port: 8080
spring:
  application:
    name: authentication-service
  datasource:
#    url: jdbc:mysql://localhost:3306/swapselluser?createDatabaseIfNotExist=true
    url: jdbc:mysql://mysql:3306/swapselluser?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    database-platform: org.hibernate.dialect.MySQL8Dialect
  rabbitmq:
    host: rabbitmq
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
