spring:
  application:
    name: chatService
  data:
    mongodb:
      uri: mongodb://mongodb:27017
      database: SwapSellChats
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8081